from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from . import views, forms, models

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("mayasec/", views.mayasec_view, name="mayasec"),
    path("configuracoes/email/", views.email_config_view, name="email_config"),
    path("configuracoes/whatsapp/", views.whatsapp_config_view, name="whatsapp_config"),
    path("configuracoes/totalpass/", views.totalpass_config_view, name="totalpass_config"),
    path("contratos/assinar/<str:token>/", views.contrato_assinar, name="contrato_assinar"),
    path("contratos/pdf/<str:token>/", views.contrato_pdf, name="contrato_pdf"),
    path("contratos/<int:pk>/enviar-email/", views.contrato_enviar_email, name="contrato_enviar_email"),
    path("contratos/<int:pk>/assinar-local/", views.contrato_assinar_local, name="contrato_assinar_local"),
    path("contratos/<int:pk>/documento/", views.contrato_documento, name="contrato_documento"),
    path("contratos/<int:pk>/assinatura/", views.contrato_assinatura_detalhe, name="contrato_assinatura_detalhe"),
    path("perfil/", views.perfil_view, name="perfil"),
    path(
        "conta/trocar-senha/",
        auth_views.PasswordChangeView.as_view(
            template_name="registration/password_change_form.html",
            success_url=reverse_lazy("password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "conta/trocar-senha/sucesso/",
        auth_views.PasswordChangeDoneView.as_view(template_name="registration/password_change_done.html"),
        name="password_change_done",
    ),
    path("cadastros/alunos/", lambda r: views.list_view(r, models.Aluno, forms.AlunoForm, "Alunos", allow_modal=True), name="alunos_list"),
    path("cadastros/alunos/criar/", lambda r: views.create_view(r, models.Aluno, forms.AlunoForm, "alunos_list"), name="alunos_create"),
    path("cadastros/alunos/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Aluno, forms.AlunoForm, "alunos_list", pk), name="alunos_edit"),
    path("cadastros/alunos/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Aluno, "alunos_list", pk), name="alunos_delete"),
    path("cadastros/alunos/<int:pk>/ficha/", views.aluno_detail, name="alunos_detail"),
    path("cadastros/alunos/<int:pk>/autoriza-imagem/", views.aluno_autoriza_imagem_toggle, name="aluno_autoriza_imagem_toggle"),
    path("cadastros/alunos/<int:pk>/documentos/criar/", views.aluno_documento_create, name="alunos_documento_create"),
    path("cadastros/alunos/<int:pk>/documentos/whatsapp/", views.aluno_documento_whatsapp, name="alunos_documento_whatsapp"),
    path("cadastros/alunos/<int:aluno_id>/aulas-avulsas/criar/", views.aluno_aula_avulsa_create, name="alunos_aula_avulsa_create"),
    path("cadastros/alunos/<int:aluno_id>/aulas-avulsas/<int:pk>/agenda/", views.aluno_aula_avulsa_agenda, name="alunos_aula_avulsa_agenda"),
    path("cadastros/alunos/documentos/<int:pk>/excluir/", views.aluno_documento_delete, name="alunos_documento_delete"),
    path("contratos/<int:pk>/whatsapp/", views.contrato_whatsapp, name="contratos_whatsapp"),
    path("cadastros/alunos/<int:aluno_id>/evolucoes/criar/", views.aluno_evolucao_create, name="alunos_evolucao_create"),
    path("cadastros/alunos/evolucoes/<int:evolucao_id>/editar/", views.aluno_evolucao_update, name="alunos_evolucao_update"),
    path("cadastros/alunos/evolucoes/<int:evolucao_id>/excluir/", views.aluno_evolucao_delete, name="alunos_evolucao_delete"),
    path("cadastros/alunos/<int:aluno_id>/avaliacoes/criar/", views.aluno_avaliacao_create, name="alunos_avaliacao_create"),
    path("cadastros/alunos/avaliacoes/<int:avaliacao_id>/editar/", views.aluno_avaliacao_update, name="alunos_avaliacao_update"),
    path("cadastros/alunos/avaliacoes/<int:avaliacao_id>/excluir/", views.aluno_avaliacao_delete, name="alunos_avaliacao_delete"),
    path("cadastros/alunos/<int:pk>/whatsapp/", views.aluno_whatsapp_message, name="alunos_whatsapp_message"),
    path("cadastros/profissionais/", lambda r: views.list_view(r, models.Profissional, forms.ProfissionalForm, "Profissionais"), name="profissionais_list"),
    path("cadastros/profissionais/criar/", lambda r: views.create_view(r, models.Profissional, forms.ProfissionalForm, "profissionais_list"), name="profissionais_create"),
    path("cadastros/profissionais/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Profissional, forms.ProfissionalForm, "profissionais_list", pk), name="profissionais_edit"),
    path("cadastros/profissionais/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Profissional, "profissionais_list", pk), name="profissionais_delete"),
    path("cadastros/perfis-acesso/", lambda r: views.list_view(r, models.PerfilAcesso, forms.PerfilAcessoForm, "Perfis de Acesso"), name="perfis_acesso_list"),
    path("cadastros/perfis-acesso/criar/", lambda r: views.create_view(r, models.PerfilAcesso, forms.PerfilAcessoForm, "perfis_acesso_list"), name="perfis_acesso_create"),
    path("cadastros/perfis-acesso/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.PerfilAcesso, forms.PerfilAcessoForm, "perfis_acesso_list", pk), name="perfis_acesso_edit"),
    path("cadastros/perfis-acesso/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.PerfilAcesso, "perfis_acesso_list", pk), name="perfis_acesso_delete"),

    path("cadastros/tokens-integracao/", lambda r: views.list_view(r, models.IntegracaoToken, forms.IntegracaoTokenForm, "Tokens de Integracao"), name="tokens_integracao_list"),
    path("cadastros/tokens-integracao/criar/", lambda r: views.create_view(r, models.IntegracaoToken, forms.IntegracaoTokenForm, "tokens_integracao_list"), name="tokens_integracao_create"),
    path("cadastros/tokens-integracao/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.IntegracaoToken, forms.IntegracaoTokenForm, "tokens_integracao_list", pk), name="tokens_integracao_edit"),
    path("cadastros/tokens-integracao/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.IntegracaoToken, "tokens_integracao_list", pk), name="tokens_integracao_delete"),
    path("cadastros/profissoes/", lambda r: views.list_view(r, models.Profissao, forms.ProfissaoForm, "Profissoes"), name="profissoes_list"),
    path("cadastros/profissoes/criar/", lambda r: views.create_view(r, models.Profissao, forms.ProfissaoForm, "profissoes_list"), name="profissoes_create"),
    path("cadastros/profissoes/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Profissao, forms.ProfissaoForm, "profissoes_list", pk), name="profissoes_edit"),
    path("cadastros/profissoes/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Profissao, "profissoes_list", pk), name="profissoes_delete"),
    path("cadastros/unidades/", lambda r: views.list_view(r, models.Unidade, forms.UnidadeForm, "Unidades"), name="unidades_list"),
    path("cadastros/unidades/criar/", lambda r: views.create_view(r, models.Unidade, forms.UnidadeForm, "unidades_list"), name="unidades_create"),
    path("cadastros/unidades/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Unidade, forms.UnidadeForm, "unidades_list", pk), name="unidades_edit"),
    path("cadastros/unidades/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Unidade, "unidades_list", pk), name="unidades_delete"),
    path("cadastros/planos/", lambda r: views.list_view(r, models.Plano, forms.PlanoForm, "Planos"), name="planos_list"),
    path("cadastros/planos/criar/", lambda r: views.create_view(r, models.Plano, forms.PlanoForm, "planos_list"), name="planos_create"),
    path("cadastros/planos/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Plano, forms.PlanoForm, "planos_list", pk), name="planos_edit"),
    path("cadastros/planos/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Plano, "planos_list", pk), name="planos_delete"),
    path("cadastros/tipos-servico/", lambda r: views.list_view(r, models.TipoServico, forms.TipoServicoForm, "Tipos de Servico"), name="tipos_servico_list"),
    path("cadastros/tipos-servico/criar/", lambda r: views.create_view(r, models.TipoServico, forms.TipoServicoForm, "tipos_servico_list"), name="tipos_servico_create"),
    path("cadastros/tipos-servico/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.TipoServico, forms.TipoServicoForm, "tipos_servico_list", pk), name="tipos_servico_edit"),
    path("cadastros/tipos-servico/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.TipoServico, "tipos_servico_list", pk), name="tipos_servico_delete"),
    path("cadastros/horarios-studio/", views.horarios_studio_list, name="horarios_studio_list"),
    path("cadastros/horarios-studio/criar/", lambda r: views.create_view(r, models.HorarioStudio, forms.HorarioStudioForm, "horarios_studio_list"), name="horarios_studio_create"),
    path("cadastros/horarios-studio/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.HorarioStudio, forms.HorarioStudioForm, "horarios_studio_list", pk), name="horarios_studio_edit"),
    path("cadastros/horarios-studio/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.HorarioStudio, "horarios_studio_list", pk), name="horarios_studio_delete"),
    path("cadastros/horarios-studio/gerar/", views.gerar_horarios_studio, name="horarios_studio_gerar"),
    path("cadastros/horarios-funcionamento/", views.horarios_funcionamento_list, name="horarios_funcionamento_list"),
    path(
        "cadastros/horarios-funcionamento/criar/",
        lambda r: views.create_view(r, models.HorarioFuncionamento, forms.HorarioFuncionamentoForm, "horarios_funcionamento_list"),
        name="horarios_funcionamento_create",
    ),
    path("cadastros/horarios-funcionamento/gerar/", views.gerar_horarios_funcionamento, name="horarios_funcionamento_gerar"),
    path(
        "cadastros/horarios-funcionamento/<int:pk>/atualizar/",
        views.atualizar_horario_funcionamento,
        name="horarios_funcionamento_atualizar",
    ),
    path(
        "cadastros/horarios-funcionamento/<int:pk>/editar/",
        lambda r, pk: views.edit_view(r, models.HorarioFuncionamento, forms.HorarioFuncionamentoForm, "horarios_funcionamento_list", pk),
        name="horarios_funcionamento_edit",
    ),
    path(
        "cadastros/horarios-funcionamento/<int:pk>/excluir/",
        lambda r, pk: views.delete_view(r, models.HorarioFuncionamento, "horarios_funcionamento_list", pk),
        name="horarios_funcionamento_delete",
    ),
    path("cadastros/bloqueios/", views.bloqueios_list, name="bloqueios_list"),
    path("cadastros/bloqueios/criar/", views.criar_bloqueio_agenda, name="bloqueios_create"),
    path("cadastros/bloqueios/<int:pk>/atualizar/", views.atualizar_bloqueio_agenda, name="bloqueios_atualizar"),
    path(
        "cadastros/bloqueios/<int:pk>/editar/",
        lambda r, pk: views.edit_view(r, models.BloqueioAgenda, forms.BloqueioAgendaForm, "bloqueios_list", pk),
        name="bloqueios_edit",
    ),
    path(
        "cadastros/bloqueios/<int:pk>/excluir/",
        lambda r, pk: views.delete_view(r, models.BloqueioAgenda, "bloqueios_list", pk),
        name="bloqueios_delete",
    ),
    path("cadastros/termos/", views.termos_list, name="termos_list"),
    path("cadastros/termos/criar/", views.termos_create, name="termos_create"),
    path("cadastros/termos/<int:pk>/editar/", views.termos_edit, name="termos_edit"),
    path("cadastros/termos/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.TermoUso, "termos_list", pk), name="termos_delete"),
    path("cadastros/fornecedores/", lambda r: views.list_view(r, models.Fornecedor, forms.FornecedorForm, "Fornecedores"), name="fornecedores_list"),
    path("cadastros/fornecedores/criar/", lambda r: views.create_view(r, models.Fornecedor, forms.FornecedorForm, "fornecedores_list"), name="fornecedores_create"),
    path("cadastros/fornecedores/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Fornecedor, forms.FornecedorForm, "fornecedores_list", pk), name="fornecedores_edit"),
    path("cadastros/fornecedores/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Fornecedor, "fornecedores_list", pk), name="fornecedores_delete"),
    path("cadastros/categorias/", lambda r: views.list_view(r, models.Categoria, forms.CategoriaForm, "Categorias"), name="categorias_list"),
    path("cadastros/categorias/criar/", lambda r: views.create_view(r, models.Categoria, forms.CategoriaForm, "categorias_list"), name="categorias_create"),
    path("cadastros/categorias/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Categoria, forms.CategoriaForm, "categorias_list", pk), name="categorias_edit"),
    path("cadastros/categorias/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Categoria, "categorias_list", pk), name="categorias_delete"),
    path("cadastros/subcategorias/", lambda r: views.list_view(r, models.Subcategoria, forms.SubcategoriaForm, "Subcategorias"), name="subcategorias_list"),
    path("cadastros/subcategorias/criar/", lambda r: views.create_view(r, models.Subcategoria, forms.SubcategoriaForm, "subcategorias_list"), name="subcategorias_create"),
    path("cadastros/subcategorias/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Subcategoria, forms.SubcategoriaForm, "subcategorias_list", pk), name="subcategorias_edit"),
    path("cadastros/subcategorias/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Subcategoria, "subcategorias_list", pk), name="subcategorias_delete"),
    path("financeiro/contas-pagar/", views.contas_pagar_list, name="contas_pagar_list"),
    path("financeiro/contas-pagar/criar/", lambda r: views.create_view(r, models.ContasPagar, forms.ContasPagarForm, "contas_pagar_list"), name="contas_pagar_create"),
    path("financeiro/contas-pagar/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.ContasPagar, forms.ContasPagarForm, "contas_pagar_list", pk), name="contas_pagar_edit"),
    path("financeiro/contas-pagar/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.ContasPagar, "contas_pagar_list", pk), name="contas_pagar_delete"),
    path("financeiro/contas-pagar/<int:pk>/pagar/", views.efetuar_pagamento_conta_pagar, name="contas_pagar_pagar"),
    path("financeiro/contas-pagar/<int:pk>/cancelar/", views.cancelar_conta_pagar, name="contas_pagar_cancelar"),
    path("financeiro/contas-pagar/exportar-excel/", views.exportar_contas_pagar_excel, name="contas_pagar_exportar_excel"),
    path("financeiro/contas-pagar/exportar-pdf/", views.exportar_contas_pagar_pdf, name="contas_pagar_exportar_pdf"),
    path("financeiro/conta-bancaria/", views.conta_bancaria_view, name="conta_bancaria"),
    path("financeiro/conta-bancaria/criar/", views.criar_conta_bancaria, name="conta_bancaria_criar"),
    path("financeiro/conta-bancaria/movimentos/criar/", views.criar_movimento_conta, name="conta_bancaria_movimento_criar"),
    path("financeiro/fluxo-caixa/", views.fluxo_caixa_view, name="fluxo_caixa"),
    path("financeiro/fluxo-caixa/exportar-excel/", views.exportar_fluxo_caixa_excel, name="fluxo_caixa_exportar_excel"),
    path("financeiro/fluxo-caixa/exportar-pdf/", views.exportar_fluxo_caixa_pdf, name="fluxo_caixa_exportar_pdf"),
    path("financeiro/dre/", views.dre_view, name="dre_view"),
    path("financeiro/dre/relatorio/", views.dre_relatorio, name="dre_relatorio"),
    path("financeiro/dre/relatorio/exportar-excel/", views.exportar_dre_excel, name="dre_exportar_excel"),
    path("financeiro/dre/relatorio/exportar-pdf/", views.exportar_dre_pdf, name="dre_exportar_pdf"),
    path("financeiro/contas-receber/", lambda r: views.list_view(r, models.ContasReceber, forms.ContasReceberForm, "Contas a Receber"), name="contas_receber_list"),
    path("financeiro/contas-receber/criar/", lambda r: views.create_view(r, models.ContasReceber, forms.ContasReceberForm, "contas_receber_list"), name="contas_receber_create"),
    path("financeiro/contas-receber/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.ContasReceber, forms.ContasReceberForm, "contas_receber_list", pk), name="contas_receber_edit"),
    path("financeiro/contas-receber/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.ContasReceber, "contas_receber_list", pk), name="contas_receber_delete"),
    path("agenda/aulas/", views.aulas_list, name="aulas_list"),
    path("agenda/aulas/operacao/", views.aulas_operacao_api, name="aulas_operacao_api"),
    path("agenda/aulas/evolucoes/enriquecer/", views.evolucao_enriquecer_api, name="evolucao_enriquecer_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/evolucoes/", views.aula_evolucao_api, name="aulas_evolucao_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/evolucoes/enriquecer/", views.aula_evolucao_enriquecer_api, name="aulas_evolucao_enriquecer_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/avaliacoes/", views.aula_avaliacoes_api, name="aulas_avaliacoes_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/cobranca/", views.aula_cobranca_api, name="aulas_cobranca_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/historico/", views.aula_historico_api, name="aulas_historico_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/status/", views.aula_status_api, name="aulas_status_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/remarcar/", views.aula_remarcar_api, name="aulas_remarcar_api"),
    path("agenda/aulas/reservas/<int:reserva_id>/whatsapp/", views.aula_whatsapp_now_api, name="aulas_whatsapp_now_api"),
    path("integrations/totalpass/webhook/", views.totalpass_webhook, name="totalpass_webhook"),
    path("agenda/aulas/criar/", lambda r: views.create_view(r, models.AulaSessao, forms.AulaSessaoForm, "aulas_list"), name="aulas_create"),
    path("agenda/aulas/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.AulaSessao, forms.AulaSessaoForm, "aulas_list", pk), name="aulas_edit"),
    path("agenda/aulas/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.AulaSessao, "aulas_list", pk), name="aulas_delete"),
    path("contratos/", lambda r: views.list_view(r, models.Contrato, forms.ContratoForm, "Contratos"), name="contratos_list"),
    path("contratos/criar/", lambda r: views.create_view(r, models.Contrato, forms.ContratoForm, "contratos_list"), name="contratos_create"),
    path("contratos/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Contrato, forms.ContratoForm, "contratos_list", pk), name="contratos_edit"),
    path("contratos/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Contrato, "contratos_list", pk), name="contratos_delete"),
    path("contratos/<int:pk>/agenda/", views.contrato_agenda, name="contratos_agenda"),
    path("reservas/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.Reserva, forms.ReservaForm, "alunos_list", pk), name="reservas_edit"),
    path("reservas/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.Reserva, "alunos_list", pk), name="reservas_delete"),
    path("cadastros/alunos/<int:aluno_id>/reservas/excluir/", views.aluno_reservas_delete_bulk, name="alunos_reservas_delete_bulk"),
    path("financeiro/contas-receber/<int:pk>/baixar/", views.baixar_conta_receber, name="contas_receber_baixar"),
    path("financeiro/contas-receber/<int:pk>/excluir/", views.excluir_conta_receber, name="contas_receber_excluir"),
    path("financeiro/contas-receber/<int:pk>/recibo/", views.recibo_conta_receber_pdf, name="contas_receber_recibo"),
    path("financeiro/contas-receber/aluno/<int:aluno_id>/exportar-pdf/", views.exportar_contas_receber_pdf, name="contas_receber_exportar_pdf"),
    path("financeiro/contas-receber/aluno/<int:aluno_id>/exportar-excel/", views.exportar_contas_receber_excel, name="contas_receber_exportar_excel"),
    path("evolucoes/aluno/<int:aluno_id>/exportar-pdf/", views.exportar_evolucoes_pdf, name="evolucoes_exportar_pdf"),
    path("evolucoes/aluno/<int:aluno_id>/exportar-excel/", views.exportar_evolucoes_excel, name="evolucoes_exportar_excel"),

    path("contratos/modelos/", views.modelos_contrato_list, name="modelos_contrato_list"),
    path("contratos/modelos/criar/", views.modelos_contrato_create, name="modelos_contrato_create"),
    path("contratos/modelos/<int:pk>/editar/", views.modelos_contrato_edit, name="modelos_contrato_edit"),
    path("contratos/modelos/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.ModeloContrato, "modelos_contrato_list", pk), name="modelos_contrato_delete"),
    path("evolucoes/modelos/", lambda r: views.list_view(r, models.ModeloEvolucao, forms.ModeloEvolucaoForm, "Modelos de Evolucao"), name="modelos_evolucao_list"),
    path("evolucoes/modelos/criar/", lambda r: views.create_view(r, models.ModeloEvolucao, forms.ModeloEvolucaoForm, "modelos_evolucao_list"), name="modelos_evolucao_create"),
    path("evolucoes/modelos/<int:pk>/editar/", lambda r, pk: views.edit_view(r, models.ModeloEvolucao, forms.ModeloEvolucaoForm, "modelos_evolucao_list", pk), name="modelos_evolucao_edit"),
    path("evolucoes/modelos/<int:pk>/excluir/", lambda r, pk: views.delete_view(r, models.ModeloEvolucao, "modelos_evolucao_list", pk), name="modelos_evolucao_delete"),
    path("reservas/<int:pk>/evoluir/", views.evoluir_reserva, name="reservas_evoluir"),
    path("wizard/step1/", views.wizard_step1, name="wizard_step1"),
    path("wizard/step2/", views.wizard_step2, name="wizard_step2"),
    path("wizard/step3/", views.wizard_step3, name="wizard_step3"),
    path("wizard/step4/", views.wizard_step4, name="wizard_step4"),
    path("wizard/step5/", views.wizard_step5, name="wizard_step5"),
]
