# Generated by Django 6.0.1 on 2026-01-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_conta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('RESERVADA', 'RESERVADA'), ('CONCLUIDA', 'CONCLUIDA'), ('FALTOU_AVISOU', 'FALTOU_AVISOU'), ('FALTOU_SEM_AVISAR', 'FALTOU_SEM_AVISAR'), ('CANCELADA', 'CANCELADA'), ('PENDENTE', 'PENDENTE')], default='RESERVADA', max_length=20),
        ),
    ]
