# Generated by Django 6.0.1 on 2026-01-25 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_reserva_status'),
        ('core', '0022_categoria_tipo_plano_categoria'),
    ]

    operations = [
    ]
