# Generated by Django 6.0.1 on 2026-01-28 18:03

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_aluno_whatsapp_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConfiguracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evolution_url', models.URLField(blank=True)),
                ('evolution_usuario', models.CharField(blank=True, max_length=150)),
                ('evolution_senha', models.CharField(blank=True, max_length=150)),
                ('avisar_aluno', models.BooleanField(default=True)),
                ('horario_aviso_aluno', models.TimeField(default=datetime.time(19, 0))),
                ('template_aviso_aluno', models.TextField(blank=True, default='Boa noite {aluno}, amanhã temos aula de {tipo_servico} às {horario}. Podemos confirmar?')),
                ('avisar_professor', models.BooleanField(default=True)),
                ('horario_aviso_professor', models.TimeField(default=datetime.time(18, 0))),
                ('template_aviso_professor', models.TextField(blank=True, default='Resumo de amanhã: {horario} – {alunos}')),
                ('enviar_link_contrato', models.BooleanField(default=True)),
                ('template_link_contrato', models.TextField(blank=True, default='Olá {aluno}, confirme seu contrato pelo link: {link_contrato}')),
                ('avisar_renovacao', models.BooleanField(default=True)),
                ('horario_aviso_renovacao', models.TimeField(default=datetime.time(10, 0))),
                ('template_aviso_renovacao', models.TextField(blank=True, default='Seu contrato vence em {dias_restantes} dias. Deseja renovar?')),
                ('variaveis_template', models.JSONField(blank=True, default=dict, null=True)),
                ('dtCadastro', models.DateTimeField(auto_now_add=True)),
                ('unidade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_configuracao', to='core.unidade')),
            ],
            options={
                'verbose_name': 'Configuração de WhatsApp',
                'verbose_name_plural': 'Configurações de WhatsApp',
            },
        ),
    ]
