# Generated by Django 5.2.8 on 2026-02-05 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_plano_avulso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunowhatsappmessage',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated_reminder', 'Lembrete diário'), ('professor_schedule', 'Agenda do professor'), ('contract_link', 'Link do contrato'), ('contract_pdf', 'Contrato em PDF'), ('contract_renewal', 'Renovação de contrato')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='avaliacaoaluno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bloqueioagenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='horariofuncionamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
