# Generated by Django 5.2.10 on 2026-05-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_horariofuncionamento_multiservico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunowhatsappmessage',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated_reminder', 'Lembrete diário'), ('professor_schedule', 'Agenda do professor'), ('contract_link', 'Link do contrato'), ('contract_pdf', 'Contrato em PDF'), ('contract_renewal', 'Renovação de contrato'), ('student_document', 'Documento do aluno')], default='manual', max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsappagendamentolog',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('automated_reminder', 'Lembrete diário'), ('professor_schedule', 'Agenda do professor'), ('contract_link', 'Link do contrato'), ('contract_pdf', 'Contrato em PDF'), ('contract_renewal', 'Renovação de contrato'), ('student_document', 'Documento do aluno')], max_length=30),
        ),
    ]
