# Generated by Django 5.2.10 on 2026-06-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_alunowhatsappmessage_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegracaoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Empresa / Descricao')),
                ('token', models.CharField(blank=True, db_index=True, max_length=80, unique=True)),
                ('ativo', models.BooleanField(default=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='Ultimo uso')),
                ('dtCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Token de Integracao',
                'verbose_name_plural': 'Tokens de Integracao',
                'ordering': ['-dtCadastro'],
            },
        ),
    ]
