# Generated by Django 5.2.10 on 2026-06-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_integracaotoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunowhatsappmessage',
            name='direcao',
            field=models.CharField(choices=[('enviada', 'Enviada'), ('recebida', 'Recebida')], default='enviada', max_length=10),
        ),
    ]
