# Generated by Django 5.2.10 on 2026-06-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alunowhatsappmessage_direcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='template_aniversario',
            field=models.TextField(blank=True, default='Feliz Aniversário, {aluno}! 🎉\nDesejamos um ano cheio de energia boa, leveza, saúde e momentos que façam seu coração sorrir. Continue se cuidando e honrando seu corpo. É um privilégio te acompanhar nessa jornada. 🎂🎈🙏', verbose_name='Mensagem de aniversário'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='template_fim_contrato',
            field=models.TextField(blank=True, default='Olá, {aluno}! Tudo bem? 🌸\nSeu ciclo atual de Pilates está chegando ao fim e adoraríamos continuar acompanhando sua evolução! Para o próximo período, o valor do plano passou por um pequeno reajuste e será de R$ {valor}.\nPodemos confirmar sua renovação e garantir seu horário? Me avise por aqui para prepararmos o novo contrato! ✨', verbose_name='Mensagem de fim de contrato'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='template_mensalidade_atraso',
            field=models.TextField(blank=True, default='Olá! Tudo bem? Passando para lembrar que o pagamento da sua mensalidade do Pilates (vencimento em {data}) no valor de R$ {valor} ainda não consta em nosso sistema.\nPode ter sido apenas um esquecimento, mas se precisar de algo, estou à disposição! 🧘\u200d♀️\nChave Pix (CNPJ): 50.732.875/0001-56\nCaso o pagamento já tenha sido realizado, por favor, desconsidere esta mensagem.', verbose_name='Mensagem de mensalidade em atraso'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='template_tres_meses',
            field=models.TextField(blank=True, default='Olá, {aluno}! Parabéns pelos 3 meses de Pilates! 💪🏻\nSente mais força ou mobilidade? Alguma dor reduziu? Alguma nova meta que você gostaria de trabalhar?\nOs primeiros 90 dias são essenciais para criar consistência, e você está indo muito bem!\nObrigada por confiar na Mayris para cuidar de você. Conte sempre comigo!', verbose_name='Mensagem de acompanhamento (3 meses)'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='template_vencimento_proximo',
            field=models.TextField(blank=True, default='Olá, {aluno}! Tudo bem? Passando para lembrar que sua mensalidade do Pilates vence em breve, no dia {data}. Qualquer dúvida, estou à disposição. 🧘\u200d♀️✨', verbose_name='Mensagem de vencimento próximo'),
        ),
    ]
