# Generated by Django 5.2.10 on 2026-06-19 22:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_whatsappconfiguracao_template_aniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='avisar_aniversario',
            field=models.BooleanField(default=False, verbose_name='Ativar aniversário'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='avisar_atraso',
            field=models.BooleanField(default=False, verbose_name='Ativar mensalidade em atraso'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='avisar_fim_contrato',
            field=models.BooleanField(default=True, verbose_name='Ativar fim de contrato (manual)'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='avisar_tres_meses',
            field=models.BooleanField(default=False, verbose_name='Ativar acompanhamento 3 meses'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='avisar_vencimento',
            field=models.BooleanField(default=False, verbose_name='Ativar vencimento próximo'),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='horario_aviso_aniversario',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='horario_aviso_atraso',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='horario_aviso_tres_meses',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
        migrations.AddField(
            model_name='whatsappconfiguracao',
            name='horario_aviso_vencimento',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
