# Generated by Django 5.2.10 on 2026-06-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_whatsappconfiguracao_avisar_aniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='termo_assinado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='termo_assinatura_documento',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='aluno',
            name='termo_assinatura_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='assinaturas_termo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='termo_assinatura_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='termo_assinatura_nome',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
