# Generated by Django 5.2.10 on 2026-06-21 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_aluno_termo_assinado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='confirmada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='desmarcada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reposicao_ate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlunoAppCodigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6)),
                ('expira_em', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_codigos', to='core.aluno')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
