# Generated by Django 5.2.10 on 2026-06-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_reserva_confirmada_em_reserva_desmarcada_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contasreceber',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contas_avulsas', to='core.aluno'),
        ),
        migrations.AddField(
            model_name='contasreceber',
            name='descricao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
